# import = ["~/AppData/Roaming/alacritty/themes/themes/Mariana.toml"]
import = [
# "~/AppData/Roaming/alacritty/catppuccin-latte.toml"
	"~/AppData/Roaming/alacritty/catppuccin-frappe.toml"
# "~/AppData/Roaming/alacritty/catppuccin-macchiato.toml"
# "~/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12
normal.family = "MesloLGS NF"

[window]
# padding = {x = 10, y = 10}
# position = {x = 300, y = 150}
# dimensions = {columns = 152, lines = 45}
startup_mode = "Maximized"
opacity = 1
decorations = "None"
title = "Alacritty"
dynamic_title = false

[shell]
program = "C:/Windows/System32/wsl.exe"
args = ["-d", "Ubuntu-22.04", "-u", "lucas", "zsh"]

[env]
TERM = "xterm-256color"

